---
title: "Download and Install"
---
<br>

## Install PANKEGG

Installing Pankegg is simple. You can either download the repository as a zip file, or clone it using git.

### Download via wget or curl

You can download the repository as a zip file with `wget`:

```bash
wget https://github.com/RVanDamme/PANKEGG/archive/refs/heads/master.zip
unzip master.zip
cd PANKEGG-master
```
Or with `curl`:

```bash
curl -L https://github.com/RVanDamme/PANKEGG/archive/refs/heads/master.zip -o master.zip
unzip master.zip
cd PANKEGG-master
```

**OR**

### Clone via git

Alternatively, you can clone the repository directly using git:

```bash
git clone https://github.com/RVanDamme/PANKEGG.git
cd PANKEGG
```


## Install dependencies

You can install Pankegg and all necessary dependencies via **conda**, **pip**, or **pixi**.

### Using conda

For a stable installation, use [conda-lock](https://github.com/conda/conda-lock) to create and activate a stable conda environment using the provided `conda-lock.yml` file (found in the `conda.recipe` directory):

```bash
conda-lock install --name pankegg_env conda-lock.yml
conda activate pankegg_env
```

Alternatively, create and activate a new conda environment using the provided `environment.yml` file (found in the `conda.recipe` directory):

```bash
conda env create -f environment.yml
conda activate pankegg_env
```

### Using pip

From within the repository folder, install all dependencies by running:

```bash
pip install .
```

Or, install dependencies only:

```bash
pip install flask pandas numpy scikit-learn scipy jinja2 click setuptools importlib-metadata
```

### Using pixi

If you use [pixi](https://prefix.dev/docs/pixi/), you can use the `pixi.lock` and run all the Pankegg commands with:

```bash
pixi run <pankegg_command>
```

Substitube `<pankegg_command>` with the command you want to run. 

## Windows Subsystem for Linux 

If you are using WSL, you should install Pankegg in the WSL itself and **NOT on your Windows drive**. This is required because of the disparity between the Linux FileSystem and the Windows FileSystem, which prevents the tools from running correctly through WSL when installed in the Windows FS.

We also recommend storing your database in the WSL rather than on your Windows drive. While this is not critical, it is a better practice and ensures that Pankegg will read the database properly.
