---
title: "Quickstart"
---

<br>
This quickstart guide will walk you through setting up Pankegg, running the pipeline on test data, and launching the web application to explore your results.

##  Install Pankegg and Dependencies

Install Pankegg via pip, conda, or pixi.  
See the [Installation](#installation) section for detailed options.

```bash
wget https://github.com/RVanDamme/PANKEGG/archive/refs/heads/master.zip
unzip master.zip
cd PANKEGG-master
pip install .
```

## Download Example Test Data (optional)

Download and extract the example dataset:

```bash
wget https://osf.io/5v3zc/download -O pankegg_test_data.zip
unzip pankegg_test_data.zip
```

## Build the SQL Database (optional) 

Generate a Pankegg database from the provided CSV using the included test data (for both Sourmash and GTDB-TK classification):

```bash
python pankegg_make_db.py -i pankegg_test_data/sourmash_example.csv -o test_sourmash --output_dir pankegg_test_data
```

## Launch the Web Application

Start the web server using the database present in the repository:

```bash
python pankegg_app.py --d data/pankegg.db
```

or use the the database you generated in point 3:

```bash
python pankegg_app.py --d pankegg_test_data/test_sourmash
```

## Open web browser


Now, open your web browser and go to the IP address written in your terminal ( [http://0.0.0.0:5000](http://0.0.0.0:5000)) to interactively explore your metagenomic data!