name: pankegg_env
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - flask==3.1.1
  - pandas==2.2.3
  - numpy==2.2.6
  - scikit-learn==1.6.1
  - scipy==1.15.2
  - jinja2==3.1.6
  - click==8.2.1
  - pip==25.1.1
  - pip:
      - importlib-metadata==8.7.0
