package:
  name: pankegg
  version: "0.1.0"

source:
  path: ./

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - flask
    - pandas
    - numpy
    - scikit-learn
    - scipy
    - jinja2
    - click
    - importlib-metadata

test:
  requires:
    - pytest
  commands:
    - pankegg_make_db -h
  files:
    - main.py
    - data/pankegg.db
    - data/pathway_groups.txt
    - templates/base.html
    - templates/bin.html
    - templates/bin_vs_bin.html
    - templates/comp_menu.html
    - templates/compar_full.html
    - templates/index.html
    - templates/kegg.html
    - templates/map.html
    - templates/maps.html
    - templates/sample_vs_sample.html
    - templates/show_bins.html
    - templates/taxonomy.html
    - templates/taxonomy_comparison.html
    - templates/tmp_save.html
    - main.py
    - data/kegg_map_info.tsv
    - data/kegg_map_orthologs.tsv
    - data/ko.txt
    - data/pathway.txt
    - data/sample_path.csv

about:
  home: https://github.com/Avanbelle/PanKEGG.git
  license: MIT
  summary: The PanKEGG Flask application is a web-based tool for visualizing, comparing, and exporting metagenomic data related to taxonomy and pathways.
